class_name LetterAudioMap extends Resource

@export var a: AudioStreamWAV
@export var b: AudioStreamWAV
@export var c: AudioStreamWAV
@export var d: AudioStreamWAV
@export var e: AudioStreamWAV
@export var f: AudioStreamWAV
@export var g: AudioStreamWAV
@export var h: AudioStreamWAV
@export var i: AudioStreamWAV
@export var j: AudioStreamWAV
@export var k: AudioStreamWAV
@export var l: AudioStreamWAV
@export var m: AudioStreamWAV
@export var n: AudioStreamWAV
@export var o: AudioStreamWAV
@export var p: AudioStreamWAV
@export var q: AudioStreamWAV
@export var r: AudioStreamWAV
@export var s: AudioStreamWAV
@export var t: AudioStreamWAV
@export var u: AudioStreamWAV
@export var v: AudioStreamWAV
@export var w: AudioStreamWAV
@export var x: AudioStreamWAV
@export var y: AudioStreamWAV
@export var z: AudioStreamWAV
